la-mia-pizzeria-static/Controllers/Api/PizzasController.cs
using la_mia_pizzeria_static.Database;
using la_mia_pizzeria_static.Migrations;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class PizzasController : ControllerBase
    {
        private DbPizzeriaContext _pizzaDatabase;

        public PizzasController(DbPizzeriaContext pizzaDatabase)
        {
            _pizzaDatabase = pizzaDatabase;
        }

        [HttpGet]
        public IActionResult GetPizzas()
        {
            List<Pizza> allPizza = _pizzaDatabase.Pizza.Include(p => p.Ingredients).Include(p => p.Category).ToList();
            if(allPizza != null && allPizza.Count > 0)
            {
                return Ok(allPizza);
            } else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult SearchPizzas(string? searchingName)
        {
            if(searchingName != null && searchingName.Trim().Length > 0) 
            {
                List<Pizza> allPizza = _pizzaDatabase.Pizza.Where(p => p.Name.ToLower().Contains(searchingName.Trim().ToLower())).Include(p => p.Ingredients).Include(p => p.Category).ToList();
                if (allPizza != null && allPizza.Count > 0)
                {
                    return Ok(allPizza);
                }
                else
                {
                    return GetPizzas();
                }
            } else
            {
                return GetPizzas();
            }
        }

        [HttpGet("{id}")]
        public IActionResult GetPizzaById(long id)
        {
            Pizza? foundPizza = _pizzaDatabase.Pizza.Include(p => p.Ingredients).Include(p => p.Category).Where(p => p.Id == id).FirstOrDefault();
            if (foundPizza != null)
            {
                return Ok(foundPizza);
            } else 
            { 
                return NotFound(); 
            }
        }

        [HttpPost]
        public IActionResult CreatePizza([FromBody] PizzaFormModel newPizzaModel)
        {
            try
            {
                if (newPizzaModel.Pizza.UrlImage == null)
                {
                    newPizzaModel.Pizza.UrlImage = "/img/pizza_placeholder.png";
                }

                if(newPizzaModel.SelectedIngredients != null)
                {
                    newPizzaModel.Pizza.Ingredients = new List<Ingredient>();
                    foreach (String ingredientId in newPizzaModel.SelectedIngredients)
                    {
                        long parsedIngredientId = long.Parse(ingredientId);

                        Ingredient? dbIngredient = _pizzaDatabase.Ingredients.Where(i => i.Id == parsedIngredientId).FirstOrDefault();

                        if (dbIngredient != null)
                        {
                            newPizzaModel.Pizza.Ingredients.Add(dbIngredient);
                        }
                    }
                }
                _pizzaDatabase.Add(newPizzaModel.Pizza);
                _pizzaDatabase.SaveChanges();
                return Ok();
            } catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpPut("{id}")]
        public IActionResult UpdatePizza(long id, [FromBody] PizzaFormModel newPizzaModel)
        {
            try
            {
                Pizza? updatingPizza = _pizzaDatabase.Pizza.Where(p => p.Id == id).Include(pizza => pizza.Ingredients).FirstOrDefault();
                if(updatingPizza != null)
                {
                    if (newPizzaModel.Pizza.UrlImage == null)
                    {
                        newPizzaModel.Pizza.UrlImage = "/img/pizza_placeholder.png";
                    }
                    updatingPizza.Name = newPizzaModel.Pizza.Name;
                    updatingPizza.Description = newPizzaModel.Pizza.Description;
                    updatingPizza.UrlImage = newPizzaModel.Pizza.UrlImage;
                    updatingPizza.Price = newPizzaModel.Pizza.Price;
                    updatingPizza.CategoryId = newPizzaModel.Pizza.CategoryId;
                    updatingPizza.Ingredients?.Clear();
                    if (newPizzaModel.SelectedIngredients != null)
                    {
                        updatingPizza.Ingredients = new List<Ingredient>();
                        foreach (String ingredientId in newPizzaModel.SelectedIngredients)
                        {
                            long parsedIngredientId = long.Parse(ingredientId);

                            Ingredient? dbIngredient = _pizzaDatabase.Ingredients.Where(i => i.Id == parsedIngredientId).FirstOrDefault();

                            if (dbIngredient != null)
                            {
                                updatingPizza.Ingredients.Add(dbIngredient);
                            }
                        }
                    }
                    _pizzaDatabase.SaveChanges();
                    return Ok();
                } else
                {
                    return BadRequest();
                }
            } catch(Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpDelete("{id}")]
        public IActionResult DeletePizzaById(long id)
        {
            try
            {
                Pizza deletingPizza = _pizzaDatabase.Pizza.Find(id);
                if(deletingPizza != null)
                {
                    _pizzaDatabase.Remove(deletingPizza);
                    _pizzaDatabase.SaveChanges();
                    return Ok();
                }
                else
                {
                    return BadRequest();
                }
            } catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult GetCategoriesList()
        {
            List<Category> allCategories = _pizzaDatabase.Categories.ToList();
            if (allCategories != null && allCategories.Count > 0)
            {
                return Ok(allCategories);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpGet]
        public IActionResult GetIngredientsList()
        {
            List<Ingredient> allIngredients = _pizzaDatabase.Ingredients.ToList();
            if (allIngredients != null && allIngredients.Count > 0)
            {
                return Ok(allIngredients);
            }
            else
            {
                return NotFound();
            }
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.CustomLoggers;
using la_mia_pizzeria_static.Database;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {

        private ICustomLogger _logger;
        private DbPizzeriaContext _pizzaDatabase;

        public PizzaController(ICustomLogger logger, DbPizzeriaContext pizzaDatabase)
        {
            this._logger = logger;
            this._pizzaDatabase = pizzaDatabase;
        }

        public IActionResult Menu()
        {

            List<Pizza> pizzaList = new();

            
            try
            {
                pizzaList = _pizzaDatabase.Pizza.ToList();
            }
            catch (Exception ex)
            {
                //  Gestione dell'errore
            }
            

            return View("Menu", pizzaList);
        }

        [Authorize(Roles = "ADMIN,USER")]
        public IActionResult Details(long id)
        {

            
            Pizza? foundPizza = _pizzaDatabase.Pizza.Where(pizza => pizza.Id == id).Include(pizza => pizza.Category).Include(pizza => pizza.Ingredients).FirstOrDefault();

            if (foundPizza == null)
            {
                _logger.WriteFileLog($"Tentativo fallito di mostrare dettagli della pizza con id = {id}");
                return NotFound($"Non è stata trovata una pizza con id={id}.");
            }
            else
            {
                return View("Details", foundPizza);
            }
            

        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {

            List<Category> categories = _pizzaDatabase.Categories.ToList();

            PizzaFormModel model = new PizzaFormModel();

            List<Ingredient> dbIngredients = _pizzaDatabase.Ingredients.ToList();

            List<SelectListItem> availableIngredients = new List<SelectListItem>();

            if(dbIngredients != null)
            {
                foreach(Ingredient ingredient in dbIngredients)
                {
                    string ingredientStringId = ingredient.Id.ToString();

                    availableIngredients.Add(new SelectListItem { Value = ingredientStringId, Text = ingredient.Name });
                }
            }

            model.Ingredients = availableIngredients;

            model.Pizza = new Pizza();
            model.Categories = categories;

            return View("Create", model);
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaFormModel pizzaForm)
        {
            if (pizzaForm.Pizza.UrlImage == null)
            {
                pizzaForm.Pizza.UrlImage = "/img/pizza_placeholder.png";
            }
            if (!ModelState.IsValid)
            {
                List<Category> categories = _pizzaDatabase.Categories.ToList();

                List<Ingredient> dbIngredients = _pizzaDatabase.Ingredients.ToList();

                List<SelectListItem> availableIngredients = new List<SelectListItem>();

                if (dbIngredients != null)
                {
                    foreach (Ingredient ingredient in dbIngredients)
                    {
                        string ingredientStringId = ingredient.Id.ToString();

                        availableIngredients.Add(new SelectListItem { Value = ingredientStringId, Text = ingredient.Name });
                    }
                }

                pizzaForm.Ingredients = availableIngredients;
                pizzaForm.Categories = categories;

                return View("Create", pizzaForm);
            }

            Pizza newPizza = new Pizza();
            newPizza.Name = pizzaForm.Pizza.Name;
            newPizza.Description = pizzaForm.Pizza.Description;
            newPizza.UrlImage = pizzaForm.Pizza.UrlImage;
            newPizza.Price = pizzaForm.Pizza.Price;

            if (pizzaForm.Pizza.CategoryId != null)
            {
                newPizza.CategoryId = pizzaForm.Pizza.CategoryId;
            }

            newPizza.Ingredients = new List<Ingredient>(); 

            if (pizzaForm.SelectedIngredients != null)
            {
                foreach(String ingredientId in pizzaForm.SelectedIngredients)
                {
                    long parsedIngredientId = long.Parse(ingredientId);

                    Ingredient? dbIngredient = _pizzaDatabase.Ingredients.Where(i => i.Id == parsedIngredientId).FirstOrDefault();

                    if(dbIngredient != null)
                    {
                        newPizza.Ingredients.Add(dbIngredient);
                    }
                }
            }

            _pizzaDatabase.Pizza.Add(newPizza);
            _pizzaDatabase.SaveChanges();

            _logger.WriteFileLog($"Aggiunta al database una pizza con id = {pizzaForm.Pizza.Id}");

            return RedirectToAction("Index", "Home");
            
        }

        [HttpGet]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(long id)
        {
            
            Pizza? pizzaToEdit = _pizzaDatabase.Pizza.Where(p => p.Id == id).Include(pizza => pizza.Category).Include(pizza => pizza.Ingredients).FirstOrDefault();

            if(pizzaToEdit == null)
            {
                _logger.WriteFileLog($"Tentativo fallito di mostrare form di modifica della pizza con id = {id}");
                return NotFound();
            } else
            {
                List<Category> categories = _pizzaDatabase.Categories.ToList();
                List<Ingredient> dbIngredients = _pizzaDatabase.Ingredients.ToList();

                List<SelectListItem> availableIngredients = new List<SelectListItem>();

                if (dbIngredients != null)
                {
                    foreach (Ingredient ingredient in dbIngredients)
                    {
                        string ingredientStringId = ingredient.Id.ToString();

                        availableIngredients.Add(new SelectListItem { 
                            Value = ingredientStringId,
                            Text = ingredient.Name,
                            Selected = pizzaToEdit.Ingredients.Any(i => i.Id == ingredient.Id)
                        });
                    }
                }

                PizzaFormModel model = new PizzaFormModel();

                model.Ingredients = availableIngredients;
                model.Pizza = pizzaToEdit;
                model.Categories = categories;
                return View(model);
            }
            
        }

        [HttpPost]
        [Authorize(Roles = "ADMIN")]
        [ValidateAntiForgeryToken]
        public IActionResult Update(long id, PizzaFormModel updatedPizzaModel)
        {
            if (updatedPizzaModel.Pizza.UrlImage == null)
            {
                updatedPizzaModel.Pizza.UrlImage = "/img/pizza_placeholder.png";
            }
            if (!ModelState.IsValid)
            {

                List<Category> categories = _pizzaDatabase.Categories.ToList();

                List<Ingredient> dbIngredients = _pizzaDatabase.Ingredients.ToList();

                List<SelectListItem> availableIngredients = new List<SelectListItem>();

                if (dbIngredients != null)
                {
                    foreach (Ingredient ingredient in dbIngredients)
                    {
                        string ingredientStringId = ingredient.Id.ToString();

                        availableIngredients.Add(new SelectListItem { Value = ingredientStringId, Text = ingredient.Name });
                    }
                }

                updatedPizzaModel.Categories = categories;
                updatedPizzaModel.Ingredients = availableIngredients;

                _logger.WriteFileLog($"Inserimento di dati errati durante il tentativo di modifica della pizza con id = {id}");
                return View("Update", updatedPizzaModel);
            }

            
            Pizza? previousPizza = _pizzaDatabase.Pizza.Where(p => p.Id == id).Include(pizza => pizza.Ingredients).FirstOrDefault();

            if(previousPizza != null)
            {
                previousPizza.Name = updatedPizzaModel.Pizza.Name;
                previousPizza.Description = updatedPizzaModel.Pizza.Description;
                previousPizza.UrlImage = updatedPizzaModel.Pizza.UrlImage;
                previousPizza.Price = updatedPizzaModel.Pizza.Price;
                previousPizza.CategoryId = updatedPizzaModel.Pizza.CategoryId;

                if (updatedPizzaModel.Pizza.CategoryId != null)
                {
                    previousPizza.CategoryId = updatedPizzaModel.Pizza.CategoryId;
                }

                previousPizza.Ingredients?.Clear();

                if (updatedPizzaModel.SelectedIngredients != null)
                {
                    foreach (String ingredientId in updatedPizzaModel.SelectedIngredients)
                    {
                        long parsedIngredientId = long.Parse(ingredientId);

                        Ingredient? dbIngredient = _pizzaDatabase.Ingredients.Where(i => i.Id == parsedIngredientId).FirstOrDefault();

                        if (dbIngredient != null)
                        {
                            previousPizza.Ingredients.Add(dbIngredient);
                        }
                    }
                }

                _pizzaDatabase.SaveChanges();

                _logger.WriteFileLog($"Modificata con successo la pizza con id = {id}");

                return RedirectToAction("Index", "Home");
            } else
            {
                _logger.WriteFileLog($"Tentativo fallito di modifica della pizza con id = {id}");

la-mia-pizzeria-static/Views/Pizza/Create.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create new pizza";
}

@model PizzaFormModel

<div class="p-5">
    <div class="container bg-light p-3 rounded-3">
        <h1 class="ms-text-orange text-center">Crea la tua nuova pizza!</h1>
        <p class="fs-6 text-center">I campi contrassegnati da * sono obbligatori.</p>
        <form asp-controller="Pizza" asp-action="Create" method="post">
            @Html.AntiForgeryToken()
            <div class="mb-3">
                <label for="name" class="form-label">Nome *</label>
                <input type="text" class="form-control" id="name" asp-for="Pizza.Name">
                <span class="text-danger" asp-validation-for="Pizza.Name"></span>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Descrizione *</label>
                <input type="text" class="form-control" id="description" asp-for="Pizza.Description">
                <span class="text-danger" asp-validation-for="Pizza.Description"></span>
            </div>
            <div class="mb-3">
                <label for="imgUrl" class="form-label">URL immagine</label>
                <input type="text" class="form-control" id="imgUrl" asp-for="Pizza.UrlImage">
                <span class="text-danger" asp-validation-for="Pizza.UrlImage"></span>
            </div>
            <div class="mb-3">
                <label for="price" class="form-label">Prezzo (es. 5,5) *</label>
                <input type="number" step="0.1" class="form-control" id="price" asp-for="Pizza.Price">
                <span class="text-danger" asp-validation-for="Pizza.Price"></span>
            </div>
            <div class="mb-3">
                <select asp-for="Pizza.CategoryId" class="d-block">
                    <option value="">Categorie</option>
                    @foreach (Category category in Model.Categories)
                    {
                        @if (Model.Pizza.CategoryId == category.Id)
                        {
                            <option value="@category.Id" selected>@category.Name</option>
                        }
                        else
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="mb-3">
                <select asp-for="SelectedIngredients" class="d-block"
                    multiple="multiple"
                    size="10"
                    class="form-control mb-2 me-sm-2 ms-sm-3 leftList"
                    asp-items="@Model.Ingredients">
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Crea</button>
        </form>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/IndexApi.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Admin";
}

<div class="p-5">
    <div class="bg-light p-3 rounded-3">
        <h1 class="text-center mb-3">Lista delle pizze</h1>

        <div class="text-center">
            <a class="btn btn-success my-3" href="@Url.Action("CreateApi", "Pizza")">Aggiungi pizza</a>
        </div>

        <div>
            <input id="ms-search-pizza" type="text" class="form-control my-3" placeholder="Cerca pizza per nome...">
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Anteprima</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Descrizione</th>
                    <th scope="col">Prezzo</th>
                    <th scope="col">Azioni</th>
                </tr>
            </thead>
            <tbody id="ms-loading-menu">
                <tr class="text-center">
                    <td colspan="5">
                        <div class="spinner-border" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                    </td>
                </tr>
            </tbody>
            <tbody id="ms-empty-menu" class="d-none">
                <tr>
                    <td class="text-center text-danger" colspan="5">Il menù è ancora vuoto.</td>
                </tr>
            </tbody>
            <tbody id="ms-result-menu" class="d-none">

            </tbody>
        </table>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">
        const loadingMenu = document.getElementById("ms-loading-menu");
        const emptyMenu = document.getElementById("ms-empty-menu");
        const resultMenu = document.getElementById("ms-result-menu");
        const searchPizza = document.getElementById("ms-search-pizza");
        let delay;
        
        getMenuList();

        searchPizza.addEventListener("keyup", () => {
            const searchingString = searchPizza.value;
            clearTimeout(delay);
            delay = setTimeout(() => {
                getMenuList(searchingString);
            }, 1000);
        });

        function getMenuList(searchingString) {
            axios.get("/api/Pizzas/SearchPizzas", {
                params:{
                    searchingName: searchingString
                }
            })
            .then(function (response) {
                console.log(response);
                resultMenu.innerHTML = "";
                if (response.data.length > 0) {
                    response.data.forEach(pizza => {
                        resultMenu.innerHTML +=
                            `<tr>
                            <td>
                                <img class="ms-table-preview" src="${pizza.urlImage}" alt="${pizza.name}">
                            </td>
                            <td class="text-truncate">${pizza.name}</td>
                            <td class="text-truncate">${pizza.description}</td>
                            <td class="text-truncate">${pizza.price}€</td>
                            <td>
                            <a class="btn btn-sm btn-primary" href="#">
                                <i class="fa-solid fa-circle-info"></i>
                            </a>
                            <a class= "btn btn-sm btn-warning" href="#">
                                <i class="fa-solid fa-pen text-white"></i>
                            </a>
                            <form class= "d-inline-block" id = "ms-delete-${pizza.id}" method = "post">
                                <button data - bs - toggle="modal" data - bs - target="#ms-modal-delete" data - form - id="${pizza.id}" data - form - name="${pizza.name}" type = "submit" class= "btn btn-sm btn-danger ms-btn-delete">
                                    <i class="fa-solid fa-trash-can" > </i>
                                </button>
                            </form>
                            </td>
                        </tr>`;
                    });
                    loadingMenu.classList.add("d-none");
                    emptyMenu.classList.add("d-none");
                    resultMenu.classList.remove("d-none");
                } else {
                    loadingMenu.classList.add("d-none");
                    resultMenu.classList.add("d-none");
                    emptyMenu.classList.remove("d-none");
                }
            })
            .catch(function (error) {
                console.log(error);
            });
        }
    </script>
}

la-mia-pizzeria-static/Views/Pizza/Menu.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Home";
}

@model List<Pizza>

<div class="p-5">
    <div class="container my-3">
        <div class="row align-content-stretch bg-black bg-opacity-50 rounded-3">

            <h1 class="col-12 text-white text-center bg-black bg-opacity-75 rounded-top py-2">Menù</h1>
            @if(Model.Count > 0)
            {
                foreach (Pizza pizza in Model)
                {
                    <div class="col-3 p-3">
                        <div class="card h-100 overflow-hidden">
                            <img class="ms-card-img" src="@pizza.UrlImage" alt="@pizza.Name">
                            <div class="card-body d-flex flex-column justify-content-between">
                                <h5 class="card-title">@pizza.Name</h5>
                                <h6>@pizza.Price€</h6>
                                <p class="card-text text-truncate">@pizza.Description</p>
                                <div>
                                    <button class="btn btn-sm btn-primary ms-pizza-card-detail" data-bs-toggle="modal" data-bs-target="#ms-modal" data-path="@Url.Action("GetModalPizzaDetail", "Pizza", new { id = pizza.Id})">Dettagli</button>
                                    <button class="btn btn-sm btn-success">Aggiungi al carrello</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            } else
            {
                <p class="text-center fs-2">Il menù è ancora vuoto.</p>
            }

        </div>
    </div>
</div>

<div id="ms-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div id="ms-modal-content" class="modal-content">
            
        </div>
    </div>
</div>

@section Scripts {

    <script type="text/javascript">
        const btnDetail = document.getElementsByClassName("ms-pizza-card-detail");
        const myModalContent = document.getElementById("ms-modal-content");

        for (let i = 0; i < btnDetail.length; i++) {
            btnDetail[i].addEventListener("click", function (event) {
                myModalContent.innerHTML = `<div class="modal-body">
                                                <h2 class="p-5 text-center">Caricamento...</h2>
                                            </div>
                                            <div class="modal-footer">
                                                    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal"> Chiudi </button>
                                            </div>`;
                const path = btnDetail[i].getAttribute("data-path");
                axios.get(path)
                    .then(function (response) {
                        myModalContent.innerHTML = response.data;
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
            });
        }

    </script>
}

la-mia-pizzeria-static/Views/Pizza/Update.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Create new pizza";
}

@model PizzaFormModel

<div class="p-5">
    <div class="container bg-light p-3 rounded-3">
        <h1 class="ms-text-orange text-center">Modifica la tua pizza!</h1>
        <p class="fs-6 text-center">I campi contrassegnati da * sono obbligatori.</p>
        <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizza.Id" method="post">
            @Html.AntiForgeryToken()
            <input type="hidden" asp-for="Pizza.Id" />
            <div class="mb-3">
                <label for="name" class="form-label">Nome *</label>
                <input type="text" class="form-control" id="name" asp-for="Pizza.Name">
                <span class="text-danger" asp-validation-for="Pizza.Name"></span>
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Descrizione *</label>
                <input type="text" class="form-control" id="description" asp-for="Pizza.Description">
                <span class="text-danger" asp-validation-for="Pizza.Description"></span>
            </div>
            <div class="mb-3">
                <label for="imgUrl" class="form-label">URL immagine</label>
                <input type="text" class="form-control" id="imgUrl" asp-for="Pizza.UrlImage">
                <span class="text-danger" asp-validation-for="Pizza.UrlImage"></span>
            </div>
            <div class="mb-3">
                <label for="price" class="form-label">Prezzo (es. 5,5) *</label>
                <input type="number" step="0.1" class="form-control" id="price" asp-for="Pizza.Price">
                <span class="text-danger" asp-validation-for="Pizza.Price"></span>
            </div>
            <div class="mb-3">
                <select asp-for="Pizza.CategoryId" class="d-block">
                    <option value="">Categorie</option>
                    @foreach (Category category in Model.Categories)
                    {
                        @if (Model.Pizza.CategoryId == category.Id)
                        {
                            <option value="@category.Id" selected>@category.Name</option>
                        }
                        else
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="mb-3">
                <select asp-for="SelectedIngredients" class="d-block"
                        multiple="multiple"
                        size="10"
                        class="form-control mb-2 me-sm-2 ms-sm-3 leftList"
                        asp-items="@Model.Ingredients">
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
</div>